### ISSUE TITLE
Editing message should be saved when left the room.

### ISSUE THREAD

**Issue by meohyun2** [dooboolab-community/hackatalk#452]
**Specify project**
Is this `Client` issue or `Server` side issue?
Client

**Is your feature request related to a problem? Please describe.**

| editing message is not saved when leave the chatroom. if this feature added, user can remind past editing message.

https://user-images.githubusercontent.com/45916875/129470952-246cd1ce-c272-4c23-b29a-99639b002d98.MP4

**Describe the solution you'd like**

<img src = "https://user-images.githubusercontent.com/45916875/129470871-f494c620-3188-4680-96ad-0442ca2f6f81.png" width="500" height="100" />

when user re-entered the channel, user should see past editing message. (like slack draft message)

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by qkreltms** [comment]
I agree. because other chat apps are save editing messages.

**Comment by 0916dhkim** [comment]
Looks like a good idea. I think this should be stored on client side as key-value pairs (chatId, draftString).
One thing we can decide is if we want to persist it or not. For example, draft messages can be persisted inside local storage/app storage, or they can be ephemeral inside React context.

**Comment by hyochan** [comment]
Great idea! I think this can be provided with sqlite. https://docs.expo.dev/versions/latest/sdk/sqlite/

**Comment by meohyun2** [comment]
is it okay to use expo-sdk-sqlite to web page? if we maintain this feature like slack draft organizing all editing message, we should use sqlite. but if we make this feature as tiny feature, we can consider react-async-storage library.

**Comment by 0916dhkim** [comment]
@meohyun2 In that case, we probably need to use indexed DB for web & expo-sdk-sqlite for mobile. An abstraction layer (how about `DraftStore` class?) should be added for clean interface.

**Comment by hyochan** [comment]
Oh `SQLite` does not work on `web` 😞 

You can still use `AsyncStorage` but thinking on the issue again, I don't think we need storage for this. How about just supporting this as a context provider? @0916dhkim @meohyun2 

They can only live when users are using the app and throw away when the user is not using HackaTalk anymore.

**Comment by hyochan** [comment]
I think we can use [Recoil](https://recoiljs.org/ko/docs/introduction/getting-started/) in this case although it won't be stored permanently.
