### ISSUE TITLE
bug: an error alert pop-ups when click "메일 재전송" button 

### ISSUE THREAD

**Issue by qkreltms** [dooboolab-community/hackatalk#453]
**Specify project**
Server

**Describe the bug**
See screenshot

**To Reproduce**
1. make new user using graphql
```js
mutation su {
  signUp(user: {
    email: "abcd@gmail.com",
    password: "123456"
  }) {
    id, email
  }
}
```
1. login with the new email
2. move to "이메일 인증" Page
3. click "메일 재전송" button
4. an alert with error message will appear like the screenshot below

**Expected behavior**
Should authentication email send to the email again without alert.

**Screenshots**
![이메일 인증 에러](https://user-images.githubusercontent.com/25196026/129472407-ee528250-24fc-4bb8-ba28-50380365f834.PNG)

**Desktop (please complete the following information):**

- OS: WIN10 HOME
- Browser: Chrome
- Version: latest

**Comment by geoseong** [comment]
Does it work when you first sign up in your localhost?
I mean when you first try to sign up, verifying email sent to your email address well?

actually to test this email send in localhost, you need to configure your own sendgrid account and configure `SENDGRID_API_KEY`, `SENDGRID_EMAIL` prop in the `server/dotenv/.env` file.

`SENDGRID_EMAIL` is the email address like `noreply@hackatalk.dev`. so If you have configured your own sendgrid account, you need to put your email address to `SENDGRID_EMAIL`.

**related sendgrid documentation:**
Step 1. Create your account
Step 2. [Creating an API key](https://docs.sendgrid.com/ui/account-and-settings/api-keys#creating-an-api-key)
Step 3. [How to set up domain authentication](https://docs.sendgrid.com/ui/account-and-settings/how-to-set-up-domain-authentication)
extra(optional). [Getting started with the SendGrid API](https://docs.sendgrid.com/for-developers/sending-email/api-getting-started)

---
and also I found some bug in **server** code related to this issue. so you can fix and create PR on it. 👍

look at the [mutation.ts](https://github.com/dooboolab/hackatalk/blob/master/server/src/resolvers/User/mutation.ts).
- the parameter "**from**" in SendGridMail.send() method in the two resolver `sendVerification` and `findPassword` have different value.
  - one ([sendVerification](https://github.com/dooboolab/hackatalk/blob/master/server/src/resolvers/User/mutation.ts#L260)) is `SENDGRID_EMAIL` variable from `process.env`,
  ```
      const msg: MailDataRequired = {
        to: email,
        from: SENDGRID_EMAIL, <<-------
        subject: ctx.request.req.t('VERIFICATION_EMAIL_SUBJECT'),
        html,
      };

      await SendGridMail.send(msg);
  ```
  - and the other([findPassword](https://github.com/dooboolab/hackatalk/blob/master/server/src/resolvers/User/mutation.ts#L322)) is just string value(`noreply@hackatalk.dev`).
  ```
    const msg = {
      to: email,
      from: 'noreply@hackatalk.dev', <<-------
      subject: ctx.request.req.t('PASSWORD_RESET_EMAIL_SUBJECT'),
      html: getPasswordResetHTML(verificationToken, password, ctx.request.req),
    };

    try {
      await SendGridMail.send(msg);
  ```

I think the parameter in `findPassword` resolver should be replaced with **SENDGRID_EMAIL** variable for consistency.

I created my own sendgrid account and tried to replace the **from** param with my own email address in **SendGridMail.send()**, it worked well. please refer to it.
