### ISSUE TITLE
Delete messages feature

### ISSUE THREAD

**Issue by chloe-codes1** [dooboolab-community/hackatalk#462]
**Specify project**
`Client`

**Is your feature request related to a problem? Please describe.**
Hackatalk does not support deleting messages you've sent.

**Describe the solution you'd like**
I would like Hackatalk users to delete messages they didn't mean to send or send something to the wrong person

**Describe alternatives you've considered**

<img src = "https://user-images.githubusercontent.com/53922851/130347309-79c72094-c118-47ee-a3d9-3af65a9544ab.png" width="320px">

`How it works?`
- Click on message you would like to delete
- **Delete** button shows up above the message
- Confirmation modal appears when you hit the **Delete** button 
- Delete the selected message 

**Additional context**
`N/A`

**Comment by qkreltms** [comment]
It seems deleting message feature is already implemented in server.
See: 
```js
deleteMessage(
id: String!
): Message
```

**Comment by hyochan** [comment]
Yes it looks like you can try to integrate the `resolver` in client side and test it out!
